[package]
name = "mifi"
version = "0.1.0"
authors = ["Luciano <luciano.bestia@gmail.com>"]
edition = "2018"


[dependencies]
reqwest = { version = "0.10" }
tokio = { version = "0.2", features = ["full"] }