# mifi_used_data/Makefile.toml
# Workspace with members

[config]
skip_core_tasks = true

#region: public callable tasks/flows
    [tasks.default]
    description = "show list of callable public tasks"
    workspace = false
    clear = true
    dependencies = ["clear"]
    command = "cargo"
    args = ["make","--list-all-steps"]

    [tasks.dev]
    description = "cargo make dev for every workspace member"
    workspace = true
    clear = true
    dependencies = ["clear"]
    command = "cargo"
    args = ["make","dev"]

    [tasks.rundev]
    description = "runs the dev build"
    workspace = false
    clear = true
    dependencies = ["clear"]
    script = [
        "target/debug/mifi_used_data",
    ]

    [tasks.release]
    description = "cargo make release for every workspace member"
    workspace = true
    clear=true
    dependencies = ["clear"]
    command = "cargo"
    args = ["make","release"]

    [tasks.runrelease]
    description = "runs the release build"
    workspace = false
    clear = true
    dependencies = ["clear"]
    script = [
        "target/release/mifi_used_data",
    ]

    [tasks.check]
    description = "cargo make check for every workspace member"
    workspace = true
    clear=true
    dependencies = ["clear"]
    command = "cargo"
    args = ["make","check"]

    [tasks.audit]
    description = "cargo audit warnings about dependencies"
    workspace = true
    clear = true
    dependencies = [
        "clear",
        "cargo_audit",
        "workspace_audit",
    ]

    [tasks.fmt]
    description = "format source code"
    workspace = true
    clear=true
    dependencies = ["clear"]
    command = "cargo"
    args = ["make","fmt"]

    [tasks.test]
    description = "test"
    workspace = true
    clear=true
    dependencies = ["clear"]
    command = "cargo"
    args = ["make","test"]

    [tasks.doc]
    description = "build the `/target/docs` folder and copy to the `/docs` folder"
    workspace = true
    clear=true
    dependencies = [
        "clear",
        "cargo_doc",
        "cargo_docs_copy",
    ]

    [tasks.sshadd]
    description = "adds identity to ssh-agent for git and publish operations"
    workspace = false
    clear = true
    dependencies = ["clear"]
    script = [
        "ssh-add /home/luciano/.ssh/luciano_googlecloud",
        "ssh-add /home/luciano/.ssh/lucianobestia_mac",
        "ssh-add -l",
    ]

    [tasks.gitpush]
    description = "push the commits to github, uses ssh agent"
    workspace = false
    clear = true
    dependencies = ["clear"]
    script = [
        "git push",
    ]

    [tasks.udeps]
    description = "lists unused dependencies needs nightly"
    workspace = false
    clear = true
    dependencies = ["clear"]
    script = [
        "cargo +nightly udeps",
    ]

    [tasks.loc]
    description = "Lines Of Rust Code with tokei"
    workspace = false
    clear = true
    dependencies = ["clear"]
    script = [
        "tokei  -t 'Rust'",
    ]

    [tasks.depver]
    description = "list of not latest dependencies"
    workspace = false
    clear = true
    dependencies = ["clear"]
    script = [
        "cargo update --dry-run",
    ]

#endregion

[tasks.cargo_audit]
description = "cargo audit"
workspace=false
clear = true
private = true
command = "cargo"
args = ["audit"]

[tasks.workspace_audit]
description = "cargo audit for every workspace member"
workspace = true
clear=true
private=true
command = "cargo"
args = ["make","audit"]

[tasks.cargo_docs_copy]
description = "copy folder `/target/doc` to /docs folder (github standard)"
workspace=false
clear = true
private = false
script = [
    "\\rsync -avz --delete-after /mnt/c/Users/Luciano/rustprojects/mifi_used_data/target/doc/*  /mnt/c/Users/Luciano/rustprojects/mifi_used_data/docs/",
]

 [tasks.clear]
    description = "clears the screen"
    workspace = false
    clear = true
    script = [
        "clear",
    ]